### PR TITLE
add account theme.

### PR DESCRIPTION
**Pull request by gerbermichi**
## Summary

add account theme.

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog

### CODE REVIEW

**Comment by tobru** [comment]
Some things I discovered:
* The VSHN logo in the header bar should better be the white variation I guess: https://handbook.vshn.ch/hb/brand_guide.html#_white
* The password change functionality should be hidden for now
* The "Mobile Authenticator Setup" screen looks a bit squeezed, I guess it would look nicer if it uses the available space of the screen?
* Can the list of "Install one of the following applications on your mobile" be extended and linked to the respective app?

**Comment by gerbermichi** [comment]
> Can the list of "Install one of the following applications on your mobile" be extended and linked to the respective app?

The list is hard coded: 
https://github.com/keycloak/keycloak/blob/master/server-spi/src/main/java/org/keycloak/models/OTPPolicy.java

However, I could replace the entire "Template" (https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/login-config-totp.ftl). But this is not recommended.

**Comment by gerbermichi** [comment]
I fixed all other issues.

**Comment by tobru** [comment]
> However, I could replace the entire "Template"

That's not worth it. Let's leave this list then.

I just checked it out again, LGTM now :+1: 

One last question, and when the answer is "no", then it can be merged: Is it possible to change the text "Signing In" on the http://localhost:8080/auth/realms/master/account/ start page? If yes, it could be changed to "Security Settings" as title and the text below "Two-Factor Authentication".

**Comment by gerbermichi** [comment]
Thank you for your feedback. All done.

**Pull request merged**
